---
title: "Progress Report"
author: "Logan Jackson"
date: "2026-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(classdata)
library(rvest)
library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r}
library(Lahman)
head(HallOfFame, 3)
```


```{r}
HallOfFame |> filter(yearID == 2026)
```

```{r}
HallOfFame %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2026))
```

```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2026.shtml"
html <- read_html(url)
tables <- html_table(html)
head(tables[[1]], 3)
```

```{r}
data <- tables[[1]]
actual_col_names <- data[1, ]
colnames(data) <- actual_col_names
data <- data[-1, ]
head(data, 3)
```

```{r}
data$Votes <- as.numeric(data$Votes)
```

```{r}
hof_2026 <- data %>% 
  select(Name, Votes, `%vote`) %>% 
  mutate(
    yearID = 2026,
    Votes = as.numeric(Votes),
    percent_vote = readr::parse_number(`%vote`),
    inducted = ifelse(percent_vote >= 75, "Y", "N")
  )
hof_2026 <- hof_2026 |>
  mutate(Name = gsub("X-", "", Name))
hof_2026
```

```{r}
lahman_2026 <- HallOfFame %>% 
  filter(yearID == 2026)
hof_2026 %>% 
  count(inducted)
lahman_2026 %>% 
  count(votedBy, inducted)
```

```{r}
write.csv(hof_2026, file="hof_from_web.csv", row.names = FALSE)
```

```{r}
hof_2026 |>
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar()
```

```{r}
hof_2026 <- hof_2026 |> select(Name, Votes, yearID, percent_vote, inducted)

```

```{r}
theHall <- HallOfFame |> filter(yearID == 2026)
newHallOfFame <- inner_join(theHall, People, by = "playerID")
newHallOfFame
```

```{r}
newHallOfFame <- newHallOfFame |> mutate(Name = paste(nameFirst, nameLast), percent_vote = (votes / ballots) * 100 )
cutNewHallOfFame <- newHallOfFame |> select(Name, votes, yearID, percent_vote, inducted)
cutNewHallOfFame <- cutNewHallOfFame |>
  rename(Votes = votes)
cutNewHallOfFame
```

```{r}
combined2026 <- rbind(cutNewHallOfFame, hof_2026)
combined2026
```

